create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  expo_push_token text not null unique,
  platform text not null,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

create index if not exists push_tokens_profile_id_idx
  on public.push_tokens (profile_id);

alter table public.push_tokens enable row level security;

create policy "Users can manage own push tokens"
on public.push_tokens
for all
to authenticated
using ((select auth.uid()) = profile_id)
with check ((select auth.uid()) = profile_id);

grant all on table public.push_tokens to authenticated;
grant all on table public.push_tokens to service_role;
grant usage, select on sequence public.push_tokens_id_seq to authenticated;
grant usage, select on sequence public.push_tokens_id_seq to service_role;
